# Generated by Django 4.2.11 on 2024-04-24 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0016_alter_order_order_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('spec', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderDetails', to='order.order', verbose_name='Order')),
            ],
        ),
    ]
