# Generated by Django 4.2.11 on 2024-04-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=45)),
                ('product_create_at', models.DateTimeField(auto_now_add=True)),
                ('product_active_at', models.DateField(blank=True, null=True)),
                ('product_inactive_at', models.DateField(blank=True, null=True)),
                ('product_rank', models.IntegerField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('product_thumbnail', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('product_price', models.DecimalField(decimal_places=0, default=9999999999, max_digits=10)),
                ('product_desc', models.TextField(blank=True, max_length=45, null=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('-product_create_at',),
            },
        ),
    ]
