# Generated by Django 4.2.11 on 2024-04-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
