# Generated by Django 5.0.3 on 2024-04-17 16:17

from django.db import models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='related_address',
        ),
        migrations.AlterField(
            model_name='address',
            name='related_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
