# Generated by Django 5.0.3 on 2024-04-17 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_remove_address_id_remove_member_related_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='related_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
