# Generated by Django 4.2.11 on 2024-04-19 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_spec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspec',
            name='product_spec_stock',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_spec.spec', verbose_name='Product Spec'),
        ),
    ]
