# Generated by Django 4.2.11 on 2024-04-23 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('order_recipient', models.CharField(blank=True, max_length=255, null=True)),
                ('order_postal_code', models.CharField(blank=True, max_length=3, null=True)),
                ('order_address', models.CharField(blank=True, max_length=255, null=True)),
                ('order_amount', models.IntegerField(blank=True, null=True)),
                ('order_status', models.BooleanField(default=False)),
                ('order_note', models.CharField(blank=True, max_length=255, null=True)),
                ('order_trackid', models.CharField(editable=False, max_length=255)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to=settings.AUTH_USER_MODEL, verbose_name='Member')),
            ],
        ),
    ]
