# Generated by Django 4.2.11 on 2024-04-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_address',
            new_name='order_recipient_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_recipient',
        ),
        migrations.AddField(
            model_name='order',
            name='order_tel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
