# Generated by Django 4.2.11 on 2024-04-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_order_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(choices=[(True, '已送達'), (False, '配送中')], default=False),
        ),
    ]
