# Generated by Django 4.2.11 on 2024-04-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_trackid',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
