# Generated by Django 4.2.11 on 2024-04-24 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_order_id_alter_order_order_trackid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
