# Generated by Django 5.0.3 on 2024-04-20 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_product_product_desc'),
        ('product_spec', '0002_alter_productspec_product_spec_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('cid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_spec.color', verbose_name='Color')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
                ('sid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_spec.spec', verbose_name='Spec')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShopCart', to=settings.AUTH_USER_MODEL, verbose_name='Member')),
            ],
        ),
    ]
